Django/Taller/App1/urls.py
from django.urls import path
from .views import indexView, autorView

urlpatterns = [
    path('', indexView),
    path('autor/<int:id>', autorView)
]

Django/Taller/Taller/urls.py
from django.contrib import admin
from django.urls import path, include
from App1.views import indexView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('App1.urls')),
]

Django/Taller/App1/models.py
from typing import Any
from django.db import models

# Create your models here.

class AuthorDB(models.Model):
    nombre = models.CharField(max_length=50, verbose_name = 'Nombre del autor')
    fecha_nacimiento = models.DateField(verbose_name = 'Fecha de nacimiento', null = False)
    fecha_fallecimiento = models.DateField(verbose_name = 'Fecha de fallecimiento', null = True, blank = True)
    profesion = models.CharField(verbose_name = 'Profesión', max_length = 50)
    nacionalidad = models.CharField(verbose_name = 'Nacionalidad', max_length = 50)

    class Meta:
        db_table = 'Autores'
        verbose_name = 'Autor'
        verbose_name_plural = 'Autores'
    
    def __str__(self) -> str:
        return self.nombre

class FraseDB(models.Model):
    cita = models.TextField(max_length=500, verbose_name = 'Cita')
    autor_fk = models.ForeignKey(AuthorDB, on_delete = models.CASCADE)

    class Meta:
        verbose_name = 'Frase'
        verbose_name_plural = 'Frases'

    def __str__(self) -> str:
        return self.cita

Django/Taller/App1/views.py
from django.shortcuts import render, get_object_or_404
from .models import AuthorDB, FraseDB

# Create your views here.
def indexView(request):

    autor = AuthorDB.objects.all().order_by('id')

    return render(request, 'index.html', {'autor' : autor})

def autorView(request, id):

    autor = get_object_or_404(AuthorDB, id = id)
    return render(request, 'autor.html', {'autor' : autor})

Django/Taller/App1/templates/autor.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>

    <link rel="stylesheet" href="{% static 'estilos.css' %}">
</head>
<body>
   
    <h1>{{autor.nombre}}</h1>

    {% for i in autor.frasedb_set.all %} 
    
    <ul>
        <li>
            {{i.cita}}
        </li>
    </ul>
    
    {% endfor %  %}
</body>
</html>

Django/Taller/App1/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Taller</title>

    <link rel="stylesheet" href="{% static 'estilos.css' %}">
</head>
<body>
    <h1>
        Hola Mundo
    </h1>

    <br>

    <p>
        Soy una página
    </p>

    <hr>
    <ul>
    
    {% for i in autor %}

    <li><a href="autor/{{i.id}}">{{i.nombre}}</a></li>

    {% endfor %}

</ul>
    

    <script src="{% static 'script.js' %}"></script>
</body>
</html>